### ISSUE TITLE
How should we go about omitting errors or discarding entries in the timeline?

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#21]
The G.h team would like to keep a record of all data entries in the timeline and our line lists, this includes errors such as data that was later reconciled or changed by the original source. We are seeing an issue with the USDA site and data reconciliation (see tickets #20 and #15 ). For past outbreaks, the G.h team has implemented a status tab in our google sheets with an option to "discard" or "omit error" for a case. This would allow us to keep an internal record of the data entry but ensure that the public version of the data would only include active/confirmed cases. 

@scarpino is there a way we can implement this strategy into the timeline? If we were to add this feature/strategy do you need additional engineering support from our team to ensure the weekly upload does not include the omitted or discarded entries? Is there another strategy you have in mind?

**Comment by JacqSauer** [comment]
@jackie-powers do you feel comfortable closing this issue?

**Comment by jackie-powers** [comment]
@JacqSauer Yes. The public timeline occasionally includes entries by ThinkGlobalHealth that are not on our timeline. Some of these are noted on our sheet, but some are not. I will do a better job noting these additions by ThinkGlobalHealth in the future.
