### ISSUE TITLE
Mpox_Review discrepancies between WHO <> CDC data

### ISSUE THREAD

**Issue by aimeehan1** [globaldothealth/outbreak-data#36]
Curators have identified differences between WHO Regional Office for Africa [Weekly Epidemiological Reports](https://www.afro.who.int/health-topics/disease-outbreaks/outbreaks-and-other-emergencies-updates) and the Africa CDC's [Epidemic Intelligence Weekly Report](https://africacdc.org/), specifically for the DRC data related to this ongoing mpox outbreak. 

For consistency, we have used the weekly Africa CDC reports as a primary source to build our epidemiological linelist and track suspected / confirmed cases counts by location. Africa CDC reports have been released in a timely manner and presented relatively up-to-date information. 

Data enhancement is ongoing using national / local reports to identify additional, relevant metadata.

Our curation team is working to understand differences in WHO<>CDC data for countries other than DRC. This work in ongoing.

**Comment by JacqSauer** [comment]
Curator notes 2024-10-02
DRC
WHO reports 5,610 confirmed cases, ACDC reports 5,812 confirmed cases, our line list reports 5,812 confirmed cases.

Burundi
The WHO reports 853 laboratory-confirmed cases. ACDC reports 696 confirmed cases. Our line list reports 696 confirmed cases.

Nigeria
The WHO reports 78 laboratory-confirmed cases, ACDC and NCDC report 78 confirmed cases. Our line list reports 78 confirmed cases.

CAR
The WHO reports 55 laboratory-confirmed cases, ACDC reports 55 confirmed cases. Our line list reports 55 confirmed cases.

Cote d'Ivoire
The WHO reports 52 laboratory-confirmed cases, ACDC reports 62 confirmed cases. Our line list reports 62 confirmed cases.

South Africa
WHO reports 25 laboratory-confirmed cases, ACDC reports 25. Our line list reports 25 confirmed cases.

Congo
WHO reports 21 laboratory-confirmed cases, ACDC reports 21 confirmed cases. Our line list reports 21 confirmed cases.

Uganda
WHO reports 22 laboratory-confirmed cases, ACDC reports 24 confirmed cases. Our line list reports 24 confirmed cases.

Liberia
WHO reports 13 laboratory-confirmed cases, ACDC reports 12 confirmed cases. Our line list reports 12 confirmed cases.

Cameroon
WHO reports 6 laboratory-confirmed cases, Africa CDC reports 6 confirmed cases. Our line list reports 6 confirmed cases (supported by official govt sources).

Kenya
WHO reports 8 laboratory-confirmed cases, ACDC reports 5 confirmed cases. Our line list reports 5 confirmed cases.

Rwanda
WHO reports 6 laboratory-confirmed cases, ACDC reports 6 confirmed cases. Our line list reports 6 confirmed cases.

Gabon
WHO reports 2 laboratory-confirmed cases, ACDC reports 2 confirmed cases. Our line list reports 2 confirmed cases.

Guinea
WHO reports 1 laboratory-confirmed case, Africa CDC reports 1 confirmed case. Our line list reports 1 confirmed case.

Morocco
WHO is still reporting 2 laboratory-confirmed cases. Africa CDC reports 1. Our line list reports 2 confirmed cases.

The WHO reports a cumulative total of 6,754 confirmed cases, ACDC reports 6,806, our line list reports 6,810

@jackie-powers @aimeehan1 @julianasopko
