### ISSUE TITLE
DRC Total Count Discrepancy 

### ISSUE THREAD

**Issue by julianasopko** [globaldothealth/outbreak-data#44]
A discrepancy in total cases was noted. Upon review of ACDC and WHO sources we have decided not to reduce our case count until we can review the next reports numbers.

**Comment by JacqSauer** [comment]
As of 2024-09-25 the DRC cumulative counts are as follows:
Confirmed ACDC: 5599
Confirmed WHO: 5,621
Suspected ACDC: 20,668 (26267-5599)
Suspected WHO: 21,482 (27103-5621)

**Comment by aimeehan1** [comment]
NOTE: When you download the WHO's dataset, the total-confirmed-case value in their csv is cumulative. You need to check Table 2.4 in WHO's shinyapps dashboard to get the confirmed cases for 2024 only to then calculate suspected values (which Jacq lists in comment above). 

Example: WHO Download compared to Dashboard: 
![image](https://github.com/user-attachments/assets/0168ccfc-d071-4681-8e76-d37d5a38b0e0)
![image](https://github.com/user-attachments/assets/efca15ce-b461-4487-a81b-f21e4e0e0b61)

**Comment by aimeehan1** [comment]
G.h unable to resolve case count discrepancies between sources. On 05 November, G.h switched from ACDC to using WHO's mpox dashboard as the primary source of data for confirmed (and suspected) cases for DRC.
