### ISSUE TITLE
Mpox 2024 Add in Rwanda Suspected/Discarded Cases

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#48]
Rwanda is testing all suspected cases (100% test rate), but these suspected cases are not reported in the ACDC reports. Are we to assume these cases are discarded? Some earlier reports from the [RBC](https://rbc.gov.rw/weekly-bulletin/) state which cases are discarded. How do we go about this?

**Comment by aimeehan1** [comment]
Similar situation to CAR, where they reportedly have 100% test rate, and we have captured cases as discarded.

**Comment by aimeehan1** [comment]
Latest ACDC report presents a total of 1379 cases detected and tested, of which 4 were positive. If we follow CAR method, we would need to add the #difference as discarded. @JacqSauer 
![image](https://github.com/user-attachments/assets/14c8b6e5-e6ee-449e-82fb-1b13d6ae40ce)

**Comment by aimeehan1** [comment]
I also added a column for 'Discarded' cases to our pivot table so we can more easily track this data

**Comment by JacqSauer** [comment]
1,375 discarded cases were added based on the 09/23 ACDC case totals (1,379 total cases-4 confirmed cases)
