### ISSUE TITLE
Mpox Briefing Report - Add Footnote for Countries with 100% Testing Rate

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#50]
We have some countries where there is a 100% testing rate. For these countries, we assume that their cumulative case counts include confirmed and discarded (negative) cases. We would like to add a footnote to the briefing report that mentions this to show users where the cumulative totals and discarded cases are coming from. 

Here are the countries that have a 100% testing rate as of 09/23:
Central African Republic
Uganda
Rwanda

May need to add more countries after curating the 9/30 ACDC report

**Comment by JacqSauer** [comment]
Gabon also has a 100% testing rate and should be added

**Comment by abhidg** [comment]
@JacqSauer do we have an idea of the ratio of confirmed/discarded cases? Otherwise would not make much sense to plot on the same graph or add them to the global count if discarded:confirmed ratio is high. I can add a sentence to Table 1 caption for this.

**Comment by JacqSauer** [comment]
@aimeehan1 thoughts on the comment above^
