### ISSUE TITLE
Mpox 2024 Updating suspected cases for Burundi

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#51]
In the 9/30 ACDC report, it states that there are 2,087 suspected cases of which 696 were laboratory-confirmed in Burundi. This means that there are 1,391 (2087-696) suspected cases. This number is much lower than the number of suspected cases that were reported last week which was 1,418 (1468-564). There was a backlog in confirmed cases of approximately 27 cases, and this would account for the lower number of suspected cases this week (I.e., 27 of the suspected cases from last week were confirmed). 

How should we go about this?
We could add 132 new confirmed cases for Burundi and then adjust the status of 27 of the most recent suspected cases (from 9/23) as omit_error OR we can change the case status of the first 27 suspected cases from the last ACDC report to confirmed cases and then add 105 new confirmed cases for this reporting period.

Thoughts? @aimeehan1 @jackie-powers @julianasopko

**Comment by aimeehan1** [comment]
@JacqSauer I will add 132 new confirmed cases to the linelist. The Date_confirmation for these cases will be 20240930, even though some may be from previous dates. The ACDC footnote says that these cases are from backlogs of previous _weeks_, not the previous week. So, we cannot flip previously suspected cases without a specific date. I will omit-error suspected cases to match new total.

**Comment by aimeehan1** [comment]
Current count using ACDC 2024-09-30 report [2087 suspected cases, including 696 confirmed] =
696 confirmed
1391 suspected
+5 discarded (excluded from ACDC count) = 2092 total G.h cases

**Comment by aimeehan1** [comment]
Current count using ACDC 2024-10-06 report [2188 suspected cases, including 853 confirmed] =
853 confirmed
1335 suspected
**1335 is less than the current count of 1391 by 56 cases. Omit_error 56 suspected cases to make counts match. 
+5 discarded (excluded from ACDC count) = 2193 total G.h cases
