### ISSUE TITLE
Mpox 2024 - Rwanda Weekly Epi Bulletin Board Review

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#53]
Here is a summary of Rwanda's case counts following their weekly epi reports:
[Week 28](https://rbc.gov.rw/wp-content/uploads/2024/07/The-bulletin-week-28-from-8th-to-14th-July-2024.pdf), first report of mpox in Rwanda: 8 suspected cases reported by 2 health facilities 
[Week 30](https://rbc.gov.rw/wp-content/uploads/2024/08/The-bulletin-week-30-from-22nd-to-28th-July-2024.pdf): 2 confirmed cases, 15 suspected cases
[Week 31](https://rbc.gov.rw/wp-content/uploads/2024/08/The-bulletin-week-31-from-29th-July-to-4th-August-2024.pdf): 2 confirmed cases, 208 suspected cases
[Week 32](https://rbc.gov.rw/wp-content/uploads/2024/08/The-bulletin-week-32-from-5th-to-11th-August-2024.pdf): 4 confirmed cases, 170 (new?) suspected cases: "170 suspected cases of Mpox had been reported in 97 health facilities in week 32, they were tested negative in laboratory"
[Week 33](https://rbc.gov.rw/wp-content/uploads/2024/08/The-bulletin-week-33-from-12th-to-18th-August-2024.pdf) 4 confirmed cases (two have been treated, cured, and discharged), 539 total suspected cases (156 new suspected cases)
[Week 34](https://rbc.gov.rw/wp-content/uploads/2024/09/The-bulletin-week-34-from-19th-to-25th-August-2024.pdf): 4 confirmed cases, and 748 total suspected cases (209 new suspected cases)
[Week 35](https://rbc.gov.rw/wp-content/uploads/2024/09/The-bulletin-week-35-from-26th-August-to-1st-September-2024.pdf): 4 confirmed cases (all cases have been treated and discharged), 1116 total suspected cases (388 new suspected cases)
[Week 36](https://rbc.gov.rw/wp-content/uploads/2024/09/The-bulletin-week-36-from-2nd-to-6th-September-2024.pdf): 4 confirmed cases, 1,379 total suspected cases (263 new suspected cases)
[Week 37](https://rbc.gov.rw/wp-content/uploads/2024/09/The-bulletin-week-37-from-9th-to-15th-September-2024.pdf): 6 confirmed cases (2 new confirmed cases, isolated and being treated) and 1,739 suspected cases (360 new suspected cases).

our line list reflects the most recent confirmed and suspected case counts reported in week 37

**Comment by aimeehan1** [comment]
@JacqSauer I think our suspected cases should reflect these report dates in our tracker so we can see the trend in cases over time. So, not every suspected case would have the 2024-09-15 Date_report (only the 360 new suspected cases for this time period).  We would go back to the first Week 28 report and adjust the suspected counts (n=8) to reflect that Date_report, then Week 30 (n=15) and so on.
Make sense? @jackie-powers @julianasopko

**Comment by jackie-powers** [comment]
New suspected cases and cumulative suspected case counts don't add up some weeks. We will use our rule of thumb of adding the appropriate number of suspected cases to match the cumulative count. Prior to week 33, the bulletins do not explicitly label the cases as "new" or "cumulative total." Therefore, we will treat the cases from weeks 28-32 as new cases meaning that there are 401 cumulative cases as of week 32. After week 32, we will add the number of suspected cases to match the reported cumulative total.

**Comment by jackie-powers** [comment]
Update 10/7/24: The date of report has been updated for Rwanda's suspected cases to show changes in cases over time.
