### ISSUE TITLE
Mpox 2024: Ensuring that WHO and line list totals match

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#58]
Our team has discussed updating our line list so that our cumulative confirmed, suspected, and overall case counts match the [WHO weekly dashboard](https://worldhealthorg.shinyapps.io/mpx_global/). Here are the countries as of October 27th in the WHO, please check off the ones in our line list that match once they have been updated:
***edited to represent numbers as of 2024-11-03
- [x] Democratic Republic of Congo (8,662 confirmed, 39,501 total)
- [x] Burundi (1,726 confirmed, 3,679 total)
- [x] Nigeria (118 confirmed, 1,442 total)
- [x] Cote d'Ivoire (91 confirmed, 402 total)
- [x] Central African Republic (64 confirmed, 387 total)
- [x] Uganda (359 confirmed, 459 total) *this may be hard to match, we have more cases in the discarded pile
- [x] Liberia (23 confirmed, 274 total)
- [x] Kenya (14 confirmed, 244 total)
- [x] Congo (22 confirmed, 221 total)
- [x] Cameroon (6 confirmed, 98 total)
- [x] South Africa (25 confirmed, 25 total)
- [x] Gabon (2 confirmed, 15 total) *this may be hard to match, need to omit cases
- [x] Ghana (2 confirmed, 10 total) *may be hard to match, need to omit cases
- [x] Guinea (1 confirmed, 8 total)
- [x] Rwanda (26 confirmed, 26 total) *may be hard to match, we have more cases in the discarded pile. WHO is only reporting confirmed cases, may reflect a 100% testing rate
- [x] Zimbabwe (2 confirmed, 2 total)
- [x] Zambia (1 confirmed, 1 total)
- [x] Morocco (3 confirmed)

**Comment by aimeehan1** [comment]
Ghana is a country where we used [WHO data](https://www.who.int/docs/default-source/coronaviruse/situation-reports/20241013_mpox-external-sitrep_-40.pdf?sfvrsn=20b50f96_3&download=true) from their October 13th SitRep to confirm the 230 discarded (identified as suspected by source) that's in our G.h linelist. 

I will adjust our discarded case status to suspected and keep the total number presented by WHO in their SitRep.   

We can discuss if we would like to reduce the suspected count that is provided in the WHO SitRep to match the WHO's dashboard (.csv file)

**Comment by aimeehan1** [comment]
G.h is using official data for suspected cases from the **Rwanda** Ministry of Health since WHO has not included suspected cases for Rwanda in their reporting

**Comment by aimeehan1** [comment]
For curation discussion, now that G.h suspected counts match WHO counts (for most countries), we can consider if we want to change backdates of Date_report to align with the weekly incremental increases we observe in the WHO's .csv file.

**Comment by aimeehan1** [comment]
The latest WHO Mpox dashboard [data as of 17 November] did not include suspected case counts, for all countries except the DRC.  The G.h dataset reflects suspected case counts from the WHO Mpox dashboard using data as of 10 November 2024. G.h has stopped reporting updates for suspected cases in countries where data is not provided by WHO source on 20 November 2024.
