### ISSUE TITLE
Mpox 2024 - DRC Case Count Changes in WHO CSV

### ISSUE THREAD

**Issue by JacqSauer** [globaldothealth/outbreak-data#61]
In our shared drive, we have been keeping track of the WHO dashboards and CSV files since 11/03. Below, you will see that these numbers per week change as a new CSV is uploaded:

Note the columns in order are country, iso3, week_end_date, total_confirmed_cases,	total_suspected_cases, total_deaths, total_suspected_deaths, new_confirmed_cases, new_suspected_cases, new_deaths, and new_suspected_deaths

11/03/2024
![image](https://github.com/user-attachments/assets/9a2c18b8-ce23-407f-badc-1ee993d505bd)
11/10/2024
![image](https://github.com/user-attachments/assets/67d79ce2-bbb8-4ea4-86d1-d64b304902df)
11/17/2024
![image](https://github.com/user-attachments/assets/ced6aec9-5f0e-4724-8036-442a8a96185d)
I'm not sure how far back we want to go, as the total number of cases changes each week starting in January 2024 across all the CSVs. If we were to just add the cases for this week, we would be adding 1,130 new confirmed cases, which is a sharp increase. This number is a lot larger for new suspected cases. For the current week (11/17/2024) cases will be added in weekly increments until the total number of confirmed cases in our line list matches the total number of confirmed cases in the WHO CSV/dashboard (10,587). 

Another issue that I have observed is that the WHO cumulative case count is suddenly much lower than the cumulative case count we have in our line list. looking at the CSV files and the recent screenshots, it appears the confirmed case count totals have increased but the total suspected case counts have decreased. How should we go about this issue?

**Comment by aimeehan1** [comment]
Continuing to save these files and capture screenshots is the best way to verify our dataset week to week. Changing datasets without explanation is a frustrating and confusing part of our jobs as curators!

For the 17 November update, even though it was a significant decrease (thousands of cases), I changed status from suspected to omit_error to match the new (lower) cumulative case count. 

G.h case data aligns with WHO dashboard data as of 17 November: Total Cases in 2024 (n=40,120); Confirmed cases (n=10,587); Suspected cases (n=29,533).

**Comment by aimeehan1** [comment]
WHO numbers changed again!
Their dashboard still reports data as of 17 November, but the site has been updated (and the .csv file) showing 21 November date. 

G.h case data aligns with (the updated) WHO dashboard data as of 17 November: Total Cases in 2024 (n=43,862); Confirmed cases (n=9,513); suspected cases (n=34,349). G.h case counts will jump quite a bit, up and down by thousands of cases.
